# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies for fetch the details from pom.xml
      run: |
        sudo apt-get install xml2
    - name: Set variables
        id: variables
        run: |
          echo ::set-output name=version::`xml2 < pom.xml  | grep /project/version= | sed 's/.*=//'`
    - name: 
      run: xml2 < pom.xml  | grep /project/version= | sed 's/.*=//'
    - name: Build with Maven to create Greeter and Mortal contract
      run: mvn web3j:generate-sources --file pom.xml
    - name: Build with Maven
      run: mvn install --file pom.xml
    - name: Build with Maven
      run: echo VERSION=${{ steps.variables.outputs.version }}
