# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: MULESOFT API BUILD & DEPLOYMENT

on:
  push:
    branches: 
     - master
     - develop

jobs:
  ValidatePomVersion:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies for fetch the details from pom.xml
      run: |
        sudo apt-get install xml2
    - name: Set variables
      id: variables
      run: |
       echo ::set-output name=version::`xml2 < pom.xml  | grep /project/version= | sed 's/.*=//'`
    - name: Build with Maven to create Greeter and Mortal contract
      run: echo VERSION=${{ steps.variables.outputs.version }}
    - name: Test image with Aquasec microscanner
      run: |
        wget --retry-connrefused --waitretry=1 --read-timeout=5 --timeout=5 --tries=10 https://raw.githubusercontent.com/rkum79/shell_scripts/master/version_check.sh && chmod +x version_check.sh
    - name: Update version
      run: sh ./version_check.sh
  MunitValidation:
    runs-on: ubuntu-latest
    needs: [ValidatePomVersion]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven to create Greeter and Mortal contract
      run: mvn web3j:generate-sources --file pom.xml

  BUILD:
    runs-on: ubuntu-latest
    needs: [ValidatePomVersion]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven to create Greeter and Mortal contract
      run: mvn web3j:generate-sources --file pom.xml
    - name: Build with Maven
      run: mvn install --file pom.xml
    - name: Copy Artifact
      run: mkdir prod-api && cp target/*jar prod-api
    - uses: actions/upload-artifact@v1
      with:
         name: Mule-API
         path: prod-api
