# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: MULESOFT API BUILD & DEPLOYMENT

on:
  push:
    branches: 
     - master # For Prod environment afyer release it will deploy the PreProd also
     - develop # For Dev/QA environment
     - release* # For Stage Environment
  pull_request:
    branches: [ master ]
jobs:
  PreBuild:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies for fetch the details from pom.xml
      run: |
        sudo apt-get install xml2
    - name: Set variables
      id: variables
      run: |
       echo ::set-output name=version::`xml2 < pom.xml  | grep /project/version= | sed 's/.*=//'`
       echo ::set-output name=gitlog::`git tag -l |egrep -iwo 1.0.0`
    - name: Build with Maven to create Greeter and Mortal contract
      run: 
       echo VERSION=${{ steps.variables.outputs.version }}
       echo GITLOG=${{ steps.variables.outputs.gitlog }}
    - name: Download Script to check the Pre
      run: |
        wget --retry-connrefused --waitretry=1 --read-timeout=5 --timeout=5 --tries=10 https://raw.githubusercontent.com/rkum79/shell_scripts/master/version_check.sh && chmod +x version_check.sh
    - name: Update version
      run: sh ./version_check.sh
  Munit:
    runs-on: ubuntu-latest
    needs: [PreBuild]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven to create Greeter and Mortal contract
      run: mvn web3j:generate-sources --file pom.xml

  BUILD:
    runs-on: ubuntu-latest
    needs: [PreBuild]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven to create Greeter and Mortal contract
      run: mvn web3j:generate-sources --file pom.xml
    - name: Build with Maven
      run: mvn install --file pom.xml
    - name: Copy Artifact
      run: mkdir prod-api && cp target/*jar prod-api
    - uses: actions/upload-artifact@v1
      with:
         name: Mule-API
         path: prod-api
    - uses: ./
      with:
         github-token: ${{ github.token }}
         ms-teams-webhook-uri: "https://teams.microsoft.com/l/channel/19%3adf802028bd2c496d9892dc7b51c0f3d8%40thread.tacv2/General?groupId=e3bb426d-7f52-4827-aa48-efe95a5b060a&tenantId=d52c9ea1-7c21-47b1-82a3-33a74b1f74b8"
         notification-summary: OMG!! Something Exploded
         notification-color: dc3545
         timezone: America/Denver 
  TAG_Creation:
    runs-on: ubuntu-latest
    needs: [Munit, BUILD]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies for fetch the details from pom.xml
      run: |
        sudo apt-get install xml2
    - name: Download Script to create tag
      run: |
        wget --retry-connrefused --waitretry=1 --read-timeout=5 --timeout=5 --tries=10 https://raw.githubusercontent.com/rkum79/shell_scripts/master/postbuild_createtag,sh && chmod +x postbuild_createtag,sh
    - name: Update version
      run: sh ./postbuild_createtag,sh
